name: json_to_dart_class_class
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/AyoubSmina/json_to_dart_class

license: MIT

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
